// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace BuildingManagement
{
    partial class DomainClassACBase
    {
        public void Execute(string command)
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference
            var invokeParams = new {
                command = command
            };
            string payload = Newtonsoft.Json.JsonConvert.SerializeObject(invokeParams);
            var resultOfInvocation = azureIoTHubWrapper.InvokeOperation("Execute", payload, Attr_AirConId).Result;
            int statusOfInvocationResult = resultOfInvocation.status;
            logger?.LogInfo($"Result of Execute invocation for '{Attr_AirConId}' status - '{statusOfInvocationResult}'");

        }


    }
}
