// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Kae.StateMachine;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;

namespace ADTTestModel
{
    partial class DomainClassTEBase
    {
        public int GetNumberOfLiefDevices()
        {
            // TODO : Let's write code!
            // Action Description on Model as a reference
            //  1 : numOfLD = 0;
            //  2 : SELECT MANY mdSet RELATED BY SELF->ME[R1.'child'];
            //  3 : FOR EACH md IN mdSet
            //  4 : 	SELECT MANY ldSet RELATED BY md->LD[R2.'measurement'];
            //  5 : 	numOfLD = numOfLD + CARDINALITY ldSet;
            //  6 : END FOR;
            //  7 : RETURN numOfLD;

            var changedStates = new List<ChangedState>();
            // Generated from action description
                // Line : 1
                var numOfLD = 0;
                // Line : 2
                var mdSet = this.LinkedR1Child() as List<DomainClassME>;

                // Line : 3
                foreach (var md in mdSet)
                {
                    // Line : 4
                    var ldSet = md.LinkedR2Measurement() as List<DomainClassLD>;

                    // Line : 5
                    numOfLD = (numOfLD + ldSet.Count());
                }

                // Line : 7
                instanceRepository.SyncChangedStates(changedStates);
                return numOfLD;


        }


    }
}
