// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
//     Updates this file cause incorrect behavior 
//     and will be lost when the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Kae.DomainModel.Csharp.Framework;
using Kae.Utility.Logging;

namespace ADTTestModel
{
    public interface SubClassR4
    {
        public DomainClassTS GetSuperClassR4();
    }

    public static class SubClassR4Factory
    {
        public static DomainClassDef CreateInstance(string classKey, InstanceRepository instanceRepository, Logger logger)
        {
            switch (classKey)
            {
                case "SC1":
                    return DomainClassSC1Base.CreateInstance(instanceRepository, logger);
                case "SC2":
                    return DomainClassSC2Base.CreateInstance(instanceRepository, logger);
                default:
                    logger.LogError($"Bad class key letter:'{classKey}' for SubClassR4");
                    break;
            }
            return null;
        }
    }
}
