// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by tool.
//     Runtime Version : 1.0.0
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using Azure.Core;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage.AzureDigitalTwins;
using Kae.Utility.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BuildingManagement.Adaptor
{
    public class BuildingManagementAzureDigitalTwinsAdaptor : AzureDigitalTwinsAdaptor
    {

        Dictionary<string, string> cClassToTwinModel = new Dictionary<string, string>()
        {
            { "AT", "dtmi:com:kae_made:BuildingManagement:AT;1" },
            { "MI", "dtmi:com:kae_made:BuildingManagement:MI;1" },
            { "R", "dtmi:com:kae_made:BuildingManagement:R;1" },
            { "F", "dtmi:com:kae_made:BuildingManagement:F;1" },
            { "B", "dtmi:com:kae_made:BuildingManagement:B;1" },
            { "AC", "dtmi:com:kae_made:BuildingManagement:AC;1" },
            { "CE", "dtmi:com:kae_made:BuildingManagement:CE;1" },
            { "CS", "dtmi:com:kae_made:BuildingManagement:CS;1" },
            { "LC", "dtmi:com:kae_made:BuildingManagement:LC;1" },
            { "WA", "dtmi:com:kae_made:BuildingManagement:WA;1" },
            { "WL", "dtmi:com:kae_made:BuildingManagement:WL;1" }
        };

        Dictionary<string, DTDLRelationshipDef> cRelationshipToTwinRelationships = new Dictionary<string, DTDLRelationshipDef>()
        {
            { "R1", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R1_B;1", Name="R1_B", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:F;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:B;1", FormClassKeyLetter="F", PartClassKeyLetter="B" } },
            { "R2", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R2_F;1", Name="R2_F", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:R;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:F;1", FormClassKeyLetter="R", PartClassKeyLetter="F" } },
            { "R3", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R3_R;1", Name="R3_R", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:MI;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:R;1", FormClassKeyLetter="MI", PartClassKeyLetter="R" } },
            { "R4", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R4_R;1", Name="R4_R", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:AC;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:R;1", FormClassKeyLetter="AC", PartClassKeyLetter="R" } },
            { "R5", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R5_R;1", Name="R5_R", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:WL;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:R;1", FormClassKeyLetter="WL", PartClassKeyLetter="R" } },
            { "R6_", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R6__MI;1", Name="R6__MI", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:AT;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:MI;1", FormClassKeyLetter="AT", PartClassKeyLetter="MI" } },
            { "R6_Affect", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R6_Affect_AC;1", Name="R6_Affect_AC", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:AT;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:AC;1", FormClassKeyLetter="AT", PartClassKeyLetter="AC" } },
            { "R7_Contract", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R7_Contract_WL;1", Name="R7_Contract_WL", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:WA;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:WL;1", FormClassKeyLetter="WA", PartClassKeyLetter="WL" } },
            { "R7_ResponsiblePerson", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R7_ResponsiblePerson_CE;1", Name="R7_ResponsiblePerson_CE", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:WA;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:CE;1", FormClassKeyLetter="WA", PartClassKeyLetter="CE" } },
            { "R8_", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R8__CS;1", Name="R8__CS", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:LC;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:CS;1", FormClassKeyLetter="LC", PartClassKeyLetter="CS" } },
            { "R8_", new DTDLRelationshipDef() { Id="dtmi:com:kae_made:BuildingManagement:R8__R;1", Name="R8__R", SourceTwinModelId="dtmi:com:kae_made:BuildingManagement:LC;1", TargetTwinModelId="dtmi:com:kae_made:BuildingManagement:R;1", FormClassKeyLetter="LC", PartClassKeyLetter="R" } }
        };

        public BuildingManagementAzureDigitalTwinsAdaptor(string adtInstanceUrl, TokenCredential credential, InstanceRepository repository, Logger logger) : base(adtInstanceUrl, credential, repository, logger)
        {
            ;
        }

        public override DTDLRelationshipDef GetDTDLRelationshipDef(string domainName, string relationshipName)
        {
            return cRelationshipToTwinRelationships[relationshipName];
        }

        public override string GetDTDLTwinModelId(string domainName, string classKeyLetter)
        {
            return cClassToTwinModel[classKeyLetter];
        }

    }
}
